// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "GeneratedCppIncludes.h"
#include "InputCore.generated.dep.h"
PRAGMA_DISABLE_OPTIMIZATION
PRAGMA_DISABLE_DEPRECATION_WARNINGS
void EmptyLinkFunctionForGeneratedCode1InputCore() {}
static class UEnum* ETouchType_StaticEnum()
{
	extern INPUTCORE_API class UPackage* Z_Construct_UPackage__Script_InputCore();
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_ETouchType();
		Singleton = GetStaticEnum(Z_Construct_UEnum_InputCore_ETouchType, Z_Construct_UPackage__Script_InputCore(), TEXT("ETouchType"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_ETouchType(ETouchType_StaticEnum, TEXT("/Script/InputCore"), TEXT("ETouchType"), false, nullptr, nullptr);
static class UEnum* EConsoleForGamepadLabels_StaticEnum()
{
	extern INPUTCORE_API class UPackage* Z_Construct_UPackage__Script_InputCore();
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels();
		Singleton = GetStaticEnum(Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels, Z_Construct_UPackage__Script_InputCore(), TEXT("EConsoleForGamepadLabels"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_EConsoleForGamepadLabels(EConsoleForGamepadLabels_StaticEnum, TEXT("/Script/InputCore"), TEXT("EConsoleForGamepadLabels"), false, nullptr, nullptr);
static class UEnum* ETouchIndex_StaticEnum()
{
	extern INPUTCORE_API class UPackage* Z_Construct_UPackage__Script_InputCore();
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_ETouchIndex();
		Singleton = GetStaticEnum(Z_Construct_UEnum_InputCore_ETouchIndex, Z_Construct_UPackage__Script_InputCore(), TEXT("ETouchIndex"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_ETouchIndex(ETouchIndex_StaticEnum, TEXT("/Script/InputCore"), TEXT("ETouchIndex"), false, nullptr, nullptr);
static class UEnum* EControllerHand_StaticEnum()
{
	extern INPUTCORE_API class UPackage* Z_Construct_UPackage__Script_InputCore();
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_EControllerHand();
		Singleton = GetStaticEnum(Z_Construct_UEnum_InputCore_EControllerHand, Z_Construct_UPackage__Script_InputCore(), TEXT("EControllerHand"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_EControllerHand(EControllerHand_StaticEnum, TEXT("/Script/InputCore"), TEXT("EControllerHand"), false, nullptr, nullptr);
class UScriptStruct* FKey::StaticStruct()
{
	extern INPUTCORE_API class UPackage* Z_Construct_UPackage__Script_InputCore();
	static class UScriptStruct* Singleton = NULL;
	if (!Singleton)
	{
		extern INPUTCORE_API class UScriptStruct* Z_Construct_UScriptStruct_FKey();
		extern INPUTCORE_API uint32 Get_Z_Construct_UScriptStruct_FKey_CRC();
		Singleton = GetStaticStruct(Z_Construct_UScriptStruct_FKey, Z_Construct_UPackage__Script_InputCore(), TEXT("Key"), sizeof(FKey), Get_Z_Construct_UScriptStruct_FKey_CRC());
	}
	return Singleton;
}
static FCompiledInDeferStruct Z_CompiledInDeferStruct_UScriptStruct_FKey(FKey::StaticStruct, TEXT("/Script/InputCore"), TEXT("Key"), false, nullptr, nullptr);
static struct FScriptStruct_InputCore_StaticRegisterNativesFKey
{
	FScriptStruct_InputCore_StaticRegisterNativesFKey()
	{
		UScriptStruct::DeferCppStructOps(FName(TEXT("Key")),new UScriptStruct::TCppStructOps<FKey>);
	}
} ScriptStruct_InputCore_StaticRegisterNativesFKey;
	void UInputCoreTypes::StaticRegisterNativesUInputCoreTypes()
	{
	}
	IMPLEMENT_CLASS(UInputCoreTypes, 2915283474);
#if USE_COMPILED_IN_NATIVES
// Cross Module References
	COREUOBJECT_API class UClass* Z_Construct_UClass_UObject();

	INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_ETouchType();
	INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels();
	INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_ETouchIndex();
	INPUTCORE_API class UEnum* Z_Construct_UEnum_InputCore_EControllerHand();
	INPUTCORE_API class UScriptStruct* Z_Construct_UScriptStruct_FKey();
	INPUTCORE_API class UClass* Z_Construct_UClass_UInputCoreTypes_NoRegister();
	INPUTCORE_API class UClass* Z_Construct_UClass_UInputCoreTypes();
	INPUTCORE_API class UPackage* Z_Construct_UPackage__Script_InputCore();
	UEnum* Z_Construct_UEnum_InputCore_ETouchType()
	{
		UPackage* Outer=Z_Construct_UPackage__Script_InputCore();
		extern uint32 Get_Z_Construct_UEnum_InputCore_ETouchType_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReloadOrDynamic(Outer, TEXT("ETouchType"), 0, Get_Z_Construct_UEnum_InputCore_ETouchType_CRC(), false);
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ETouchType"), RF_Public|RF_Transient|RF_MarkAsNative) UEnum(FObjectInitializer());
			TArray<TPair<FName, int64>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchType::Began")), 0));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchType::Moved")), 1));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchType::Stationary")), 2));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchType::Ended")), 3));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchType::NumTypes")), 4));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchType::ETouchType_MAX")), 5));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::Namespaced);
			ReturnEnum->CppType = TEXT("ETouchType::Type");
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
			MetaData->SetValue(ReturnEnum, TEXT("ToolTip"), TEXT("Various states of touch inputs."));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_InputCore_ETouchType_CRC() { return 3680118695U; }
	UEnum* Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels()
	{
		UPackage* Outer=Z_Construct_UPackage__Script_InputCore();
		extern uint32 Get_Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReloadOrDynamic(Outer, TEXT("EConsoleForGamepadLabels"), 0, Get_Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels_CRC(), false);
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("EConsoleForGamepadLabels"), RF_Public|RF_Transient|RF_MarkAsNative) UEnum(FObjectInitializer());
			TArray<TPair<FName, int64>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EConsoleForGamepadLabels::None")), 0));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EConsoleForGamepadLabels::XBoxOne")), 1));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EConsoleForGamepadLabels::PS4")), 2));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EConsoleForGamepadLabels::EConsoleForGamepadLabels_MAX")), 3));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::Namespaced);
			ReturnEnum->CppType = TEXT("EConsoleForGamepadLabels::Type");
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_InputCore_EConsoleForGamepadLabels_CRC() { return 4139436220U; }
	UEnum* Z_Construct_UEnum_InputCore_ETouchIndex()
	{
		UPackage* Outer=Z_Construct_UPackage__Script_InputCore();
		extern uint32 Get_Z_Construct_UEnum_InputCore_ETouchIndex_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReloadOrDynamic(Outer, TEXT("ETouchIndex"), 0, Get_Z_Construct_UEnum_InputCore_ETouchIndex_CRC(), false);
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ETouchIndex"), RF_Public|RF_Transient|RF_MarkAsNative) UEnum(FObjectInitializer());
			TArray<TPair<FName, int64>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch1")), 0));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch2")), 1));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch3")), 2));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch4")), 3));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch5")), 4));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch6")), 5));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch7")), 6));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch8")), 7));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch9")), 8));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::Touch10")), 9));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("ETouchIndex::ETouchIndex_MAX")), 10));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::Namespaced);
			ReturnEnum->CppType = TEXT("ETouchIndex::Type");
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("BlueprintType"), TEXT("true"));
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
			MetaData->SetValue(ReturnEnum, TEXT("ToolTip"), TEXT("The number of entries in ETouchIndex must match the number of touch keys defined in EKeys and NUM_TOUCH_KEYS above"));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_InputCore_ETouchIndex_CRC() { return 4113741648U; }
	UEnum* Z_Construct_UEnum_InputCore_EControllerHand()
	{
		UPackage* Outer=Z_Construct_UPackage__Script_InputCore();
		extern uint32 Get_Z_Construct_UEnum_InputCore_EControllerHand_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReloadOrDynamic(Outer, TEXT("EControllerHand"), 0, Get_Z_Construct_UEnum_InputCore_EControllerHand_CRC(), false);
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("EControllerHand"), RF_Public|RF_Transient|RF_MarkAsNative) UEnum(FObjectInitializer());
			TArray<TPair<FName, int64>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Left")), 0));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Right")), 1));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Pad")), 2));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::ExternalCamera")), 3));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Gun")), 4));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_1")), 5));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_2")), 6));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_3")), 7));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_4")), 8));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_5")), 9));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_6")), 10));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_7")), 11));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_8")), 12));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::Special_9")), 13));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EControllerHand::EControllerHand_MAX")), 14));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::EnumClass);
			ReturnEnum->CppType = TEXT("EControllerHand");
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("BlueprintType"), TEXT("true"));
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
			MetaData->SetValue(ReturnEnum, TEXT("ToolTip"), TEXT("Defines the controller hands for tracking.  Could be expanded, as needed, to facilitate non-handheld controllers"));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_InputCore_EControllerHand_CRC() { return 623180853U; }
	UScriptStruct* Z_Construct_UScriptStruct_FKey()
	{
		UPackage* Outer = Z_Construct_UPackage__Script_InputCore();
		extern uint32 Get_Z_Construct_UScriptStruct_FKey_CRC();
		static UScriptStruct* ReturnStruct = FindExistingStructIfHotReloadOrDynamic(Outer, TEXT("Key"), sizeof(FKey), Get_Z_Construct_UScriptStruct_FKey_CRC(), false);
		if (!ReturnStruct)
		{
			ReturnStruct = new(EC_InternalUseOnlyConstructor, Outer, TEXT("Key"), RF_Public|RF_Transient|RF_MarkAsNative) UScriptStruct(FObjectInitializer(), NULL, new UScriptStruct::TCppStructOps<FKey>, EStructFlags(0x00000201));
			UProperty* NewProp_KeyName = new(EC_InternalUseOnlyConstructor, ReturnStruct, TEXT("KeyName"), RF_Public|RF_Transient|RF_MarkAsNative) UNameProperty(CPP_PROPERTY_BASE(KeyName, FKey), 0x0040000000000000);
			ReturnStruct->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnStruct->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnStruct, TEXT("BlueprintType"), TEXT("true"));
			MetaData->SetValue(ReturnStruct, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
			MetaData->SetValue(NewProp_KeyName, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
#endif
		}
		return ReturnStruct;
	}
	uint32 Get_Z_Construct_UScriptStruct_FKey_CRC() { return 2129465848U; }
	UClass* Z_Construct_UClass_UInputCoreTypes_NoRegister()
	{
		return UInputCoreTypes::StaticClass();
	}
	UClass* Z_Construct_UClass_UInputCoreTypes()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UObject();
			Z_Construct_UPackage__Script_InputCore();
			OuterClass = UInputCoreTypes::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000081;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("InputCoreTypes.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/InputCoreTypes.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UInputCoreTypes(Z_Construct_UClass_UInputCoreTypes, &UInputCoreTypes::StaticClass, TEXT("UInputCoreTypes"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(UInputCoreTypes);
	UPackage* Z_Construct_UPackage__Script_InputCore()
	{
		static UPackage* ReturnPackage = NULL;
		if (!ReturnPackage)
		{
			ReturnPackage = CastChecked<UPackage>(StaticFindObjectFast(UPackage::StaticClass(), NULL, FName(TEXT("/Script/InputCore")), false, false));
			ReturnPackage->SetPackageFlags(PKG_CompiledIn | 0x00000000);
			FGuid Guid;
			Guid.A = 0x552DA1B6;
			Guid.B = 0x49647A71;
			Guid.C = 0x00000000;
			Guid.D = 0x00000000;
			ReturnPackage->SetGuid(Guid);

		}
		return ReturnPackage;
	}
#endif

PRAGMA_ENABLE_DEPRECATION_WARNINGS
